[env:m5stack-core-s3]
platform = espressif32
board = m5stack-core-s3
framework = arduino
monitor_speed = 115200

lib_deps =
    m5stack/M5Core2@^0.1.9
    esp-idf-lib/tinyusb@^0.15.0

build_flags =
    -DARDUINO_M5STACK_CORES3
    -DCFG_TUH_HID_KEYBOARD=1
    -DCFG_TUH_HID_MOUSE=1
